# conf/config.yaml
defaults:
  - data: default
  - model: ridge
  - _self_

project_name: "MLOps-HousePrices"
random_state: 42
validation_split_ratio: 0.2
mlflow_experiment_name: "House_Price_Training_Hydra"
model_registry_name: "HousePricePredictor" 